server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://39.105.35.188:3306/aliTest?useUnicode=true&characterEncoding=UTF-8
    max-active: 20
    min-idle: 10
    initial-size: 10

mybatis-plus:
  mapper-locations: mapper/*.xml
