spring:
  redis:
    database: 0
    host: 39.105.35.188
    port: 6379
    password:
    timeout: 10000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0